# Generated by Django 4.0.1 on 2022-01-16 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=255)),
                ('article_link', models.URLField()),
                ('file', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('rate', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('author',),
            },
        ),
        migrations.CreateModel(
            name='VKGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('members_count', models.PositiveIntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('site', models.CharField(max_length=255, null=True)),
                ('photo_100', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VKSource',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('vk_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VKPost',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('address', models.SlugField(max_length=255, unique=True)),
                ('pub_date', models.DateField()),
                ('text', models.TextField(blank=True, null=True)),
                ('comments', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField()),
                ('reposts', models.PositiveSmallIntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vkgroup')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
