# Generated by Django 3.0.8 on 2021-12-27 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VKGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('members_count', models.PositiveIntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('site', models.CharField(max_length=255, null=True)),
                ('photo_100', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VKSource',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('vk_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='YandexNewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.URLField(max_length=350, unique=True)),
                ('pub_date', models.DateTimeField()),
                ('hash', models.CharField(max_length=100, unique=True)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='yandexnewstopic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='yandexnewstopic',
            name='name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='yandexnewstopic',
            unique_together={('name', 'rss_url')},
        ),
        migrations.CreateModel(
            name='VKPost',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('address', models.SlugField(max_length=255, unique=True)),
                ('pub_date', models.DateField()),
                ('text', models.TextField(blank=True, null=True)),
                ('comments', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField()),
                ('reposts', models.PositiveSmallIntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VKGroup')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='TriggerNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('article_link', models.URLField()),
                ('last_update', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('news_type', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('tone_type', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=3)),
                ('tone_value', models.FloatField(default=1.0)),
                ('trigger_word', models.ManyToManyField(to='core.TriggerPhrase')),
            ],
            options={
                'verbose_name': 'Trigger news',
                'verbose_name_plural': 'Trigger news',
                'ordering': ('-last_update', '-rate'),
            },
        ),
    ]
