# Generated by Django 4.0.1 on 2022-02-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vkpost',
            options={},
        ),
        migrations.RemoveField(
            model_name='vkpost',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='vkpost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='vkpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='vkpost',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='vkpost',
            name='reposts',
        ),
    ]
