# Generated by Django 4.0.4 on 2022-05-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vkpost_options_remove_vkpost_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkpost',
            name='owner',
        ),
        migrations.DeleteModel(
            name='VKSource',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rate',
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(choices=[('VK', 'VK'), ('ELIBRARY', 'ELIBRARY'), ('KPFU', 'KPFU')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(upload_to='articles/'),
        ),
        migrations.DeleteModel(
            name='VKGroup',
        ),
        migrations.DeleteModel(
            name='VKPost',
        ),
    ]
